export const chatslistData = {
    chats: [
        {
            id: "1",
            title: "Андрей",
            text: "Изображение",
            messageFromOwner: false,
            time: "12:45",
            messageNumber: 3,
            activeClass: "",
        },
        {
            id: "2",
            title: "Киноклуб",
            text: "стикер",
            messageFromOwner: true,
            time: "10:10",
            messageNumber: 0,
            activeClass: "",
        },
        {
            id: "3",
            title: "Вадим",
            text: "Круто!",
            messageFromOwner: true,
            time: "12:42",
            messageNumber: 0,
            activeClass: "chatslist-item__active",
        },
        {
            id: "4",
            title: "Илья",
            text: "Изображение",
            messageFromOwner: false,
            time: "Пт",
            messageNumber: 3,
            activeClass: "",
        },
        {
            id: "5",
            title: "Киноклуб",
            text: "стикер",
            messageFromOwner: true,
            time: "10:10",
            messageNumber: 0,
            activeClass: "",
        },
        {
            id: "6",
            title: "Илья",
            text: "Друзья, у меня для вас особенный выпуск новостей!...",
            messageFromOwner: false,
            time: "12:42",
            messageNumber: 42,
            activeClass: "",
        },
        {
            id: "7",
            title: "Андрей",
            text: "Изображение",
            messageFromOwner: false,
            time: "12:45",
            messageNumber: 3,
            activeClass: "",
        },
        {
            id: "8",
            title: "Киноклуб",
            text: "стикер",
            messageFromOwner: true,
            time: "10:10",
            messageNumber: 0,
            activeClass: "",
        },
        {
            id: "9",
            title: "Илья",
            text: "Друзья, у меня для вас особенный выпуск новостей!...",
            messageFromOwner: false,
            time: "12:42",
            messageNumber: 42,
            activeClass: "",
        },
    ],
};
